name: Release Drafter

on:
  push:
    branches:
      - "main"
  workflow_dispatch:

jobs:
  update_release_draft:
    name: Release drafter
    runs-on: ubuntu-latest
    permissions:
      contents: write
      
    steps:
      - name: Update Release Draft
        uses: release-drafter/release-drafter@v5
        with:
          config-name: config/release-drafter.yml

        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
